name: Build
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      
      - name: Get flex 💪 and bison 🦬
        run: |
          sudo apt install flex bison libfl-dev

      - name: Make 🔧
        run: |
          make

      - name: Test 🚀
        run: |
          make test
